name: alok
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+19

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.4.0
  dio: ^5.7.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  google_sign_in: ^6.2.2
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.42
  avatar_glow: ^3.0.1
  audio_video_progress_bar: ^2.0.3
  store_redirect: ^2.0.3
  google_fonts: ^6.2.1
  just_audio_background: ^0.0.1-beta.13
  rxdart: ^0.28.0
  page_transition: ^2.1.0
  cool_alert: ^2.0.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  share_plus: ^10.0.0
  # syncfusion_flutter_core: ^27.2.2  # Downgrade to stable version
  # syncfusion_flutter_pdfviewer: ^27.2.2
  flutter_cached_pdfview: ^0.4.3
  fluttertoast: ^8.2.8
  miniplayer: ^1.0.1
  just_audio_cache: ^0.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.0
  loading_indicator: ^3.1.1
  firebase_storage: ^12.2.0
  webview_flutter: ^4.8.0
  sms_autofill: ^2.4.1
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  provider: ^6.1.2
  simple_animations: ^5.0.2
  pin_code_fields: ^8.0.1
  otp_text_field: ^1.1.3
  custom_timer: ^0.2.3
  audio_session: ^0.1.21
  firebase_messaging: ^15.1.0
  carousel_slider: ^5.0.0
  icons_launcher: ^3.0.0
  yaml:
  pdfx: ^2.6.0


  

  
  



# flutter_native_splash:
#   image: "assets/images/1024.png"
#   android_gravity: center
#   color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.11.0


# flutter_icons:
#   ios: true
#   android: true
#   image_path: "assets/images/1024.png"
#   apaptive_icon_background: "#191919"


flutter:
  uses-material-design: true
  assets:
    # - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/flags/
